security:
    user:
        password: password
    oauth2:
        client:
            client-id: clientview
            client-secret: predix
        resource:
            id: service
            userInfoUri: https://a9486881-3d6a-4d0f-9617-38c59a612682.predix-uaa.run.aws-usw02-pr.ice.predix.io/userinfo
            token-info-uri: https://a9486881-3d6a-4d0f-9617-38c59a612682.predix-uaa.run.aws-usw02-pr.ice.predix.io/check_token
